### ISSUE TITLE
Cross: Github Actions [Spike]

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#1]
AS A Developer
I WANT TO Understand how I can achieve CI/CD Goals with GitHub Actions
SO THAT WE can put this knowledge to good use with our CI/CD implementations in our Buerokratt Repos

- [x] Investigate multi-stage deployment pipelines using Actions
- [x] Secret handling and configuration in CI/CD
- [x] Versioning in CI pipelines (code based and container based)
- [x] Storing Artifacts (writing and reading)
- [x] Workflows calling other workflows with parameters
- [ ] Document and share findings with the team

**Comment by LNOXS07** [comment]
@guypritchard to describe the issue.

**Comment by guypritchard** [comment]
@Adele-Churchill-13 this is the spike we were talking about.
