### ISSUE TITLE
Cross: CI Design Documentation

### ISSUE THREAD

**Issue by LNOXS07** [buerokratt/Cross-functional-requirements#18]
AS A system integrator
I WANT a design for CI pipelines that is consistent with other repositories in Burokratt
SO THAT I can implement a CI pipeline as required

## Acceptance Criteria

- [x] Document detailing CI pipeline approach

**Comment by LNOXS07** [comment]
@yahya130 and @decodingahmed to support @keijoraamat with documentation

**Comment by keijoraamat** [comment]
This gives probably input to the strategy https://github.com/buerokratt/Cross-functional-requirements/blame/main/docs/technical/unit-testing-strategy.md#L33

**Comment by martinkearn** [comment]
@yahya130 and @keijoraamat .... do you have some time today (Tuesday) to sync with me on this ticket?

**Comment by martinkearn** [comment]
Some things that the CI could include

- `dotnet restore` and build and test
- `dotnet format` for style rules (StyleCop or others).
- Stryker.net for mutation testing. Pre-project spike to lean on
