### ISSUE TITLE
Cross: CD Design Documentation

### ISSUE THREAD

**Issue by LNOXS07** [buerokratt/Cross-functional-requirements#19]
AS A Developer
I WANT TO have documentation about CD pipelines
SO THAT I can build pipeline what functions as everybody thinks it does

### Acceptance Criteria 
- [x] The document describes in general what CD pipeline does

**Comment by LNOXS07** [comment]
@keijoraamat to own with support from @yahya130 @decodingahmed

**Comment by adelechurchill** [comment]
About half-way through, needs details adding on the steps in the pipeline
Please see here: https://github.com/buerokratt/Cross-functional-requirements/pull/79
