### ISSUE TITLE
Cross: Minimum Open API spec

### ISSUE THREAD

**Issue by LNOXS07** [buerokratt/Cross-functional-requirements#22]
AS A Developer
I WANT TO have a single source of truth covering all API resources used within project
SO THAT I can be sure that my developments are compatible with other developments

### Acceptance Criteria

- [x] Create base OpenAPI spec
- [x] Specs are OpenAPI 3.0.3 compatible and can be used with Swagger UI
- [x] Spec covers the full scope of services needed for MVP 1
- [x] Covers the basic chatflow

**Comment by LNOXS07** [comment]
Action 06.05: @turnerrainer to complete. Not a blocker. Target completion date Tue 10.05.

**Comment by shelabd** [comment]
To be split into replicas for each major component by @shelabd

**Comment by shelabd** [comment]
@tonistuulNG Can you check these off when you're done with spec

**Comment by decodingahmed** [comment]
All acceptance criteria have been completed
