### ISSUE TITLE
Cross: PR policies

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#24]
AS A Developer
I WANT TO implement Pull Request policies which prevent unreviewed code from being committed to the main branch
SO THAT we can ensure that only agreed upon changes are committed.

- [ ] modify the Github subscription to allow for PR policies to be implemented
- [ ] Add this policy to the CentOps repo(s).
- [ ] Output: document describing PR policies

**Comment by martinkearn** [comment]
@turnerrainer / @keijoraamat I believe this task is done now isn't it?

**Comment by martinkearn** [comment]
Closing this as it has been addressed
