### ISSUE TITLE
Cross: Access/setup container registry

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#3]
AS A Development team
WE WANT TO have a central/secure container registry for each of the docker images produced in the Buerokratt engagement
SO THAT we have a place to store docker images output by our CI pipelines and to be deployed in CD pipelines.

- [ ] Create registries for CentOps API
- [ ] Create registry for DMR API
- [ ] Create appropriate policies for reading and writing to the registries.

**Comment by keijoraamat** [comment]
If we are using GitHubs container registry for containers from public repos, do we need reading policies?
