### ISSUE TITLE
Fix terraform pipeline

### ISSUE THREAD

**Issue by yahya130** [buerokratt/Cross-functional-requirements#32]
This task is to be tested locally (personal repo) at this moment in time since Azure and Github setup is still in progress 

AS a developer I want to be able to run the terraform-deploy pipeline within the cross-functional-requirements repository and this pipeline should run successfully deploying resources to the specified Azure resource group

- [x] Run the pipeline and test that it deploys correctly to the resource group in azure portal

**Comment by shelabd** [comment]
Add description
