### ISSUE TITLE
Cross: Test out End-to-End flow

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#45]
As as a DEVELOPER
I want to ensure that the DMR and participants can be setup easily 
So that the system communicates with each other appropriately 

We want to create a docker compose file which will start all of the containers locally and configure them accordingly.

We'll also use this task as a way to ensure that all services communicate correctly and fix bugs where we find them.

### Acceptance Criteria

- [x] Ensure all containers are communicating appropriately 
- [x] Docker compose file

(Note: Storing the docker file TBD)

**Comment by shelabd** [comment]
For the time being we'll share docker compose in the teams channel. To decide on the repo structure after Milestone 1.

**Comment by martinkearn** [comment]
@guypritchard / @shelabd ... if think this issue would benefit from a little more detail if possible. Right now, i would not know how to take this task on myself

**Comment by guypritchard** [comment]
PRs are in other repos:

DMR:
https://github.com/buerokratt/DMR/pull/41

MockBot:  
https://github.com/buerokratt/Mock-Bot/pull/25
