### ISSUE TITLE
Cross: Common library for shared models and constants

### ISSUE THREAD

**Issue by martinkearn** [buerokratt/Cross-functional-requirements#46]
AS A Developer
I WANT a common library to use for shared models, and constants across the entire Burokratt solution
SO THAT I can avoid duplicating code and have a single place to make updates to shared items

## AC

- [x] Shared library for models and constants
- [ ] Used by all .net code projects

**Comment by martinkearn** [comment]
There is overlap here with https://github.com/buerokratt/DMR/issues/30. They could both be in the same NuGet package

**Comment by joonasroosalung** [comment]
First task is covered by https://github.com/buerokratt/Request-Processor/issues/1
Second task is covered by https://github.com/buerokratt/Request-Processor/issues/2
