### ISSUE TITLE
Cross: Setting up Azure

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#5]
AS A developer
I WANT access Azure
SO THAT I can read/contribute to resources on Azure platform

- [x] Users are added and roles assigned accordingly
- [x] Create resource group on Azure (suggested name: rg-beurokratt-dev )
- [x] Create storage account (suggested name: storage-account-beurokratt-dev)
- [x] container (container-terraform-beurokratt-dev) on Azure manually to store the terraform state file

**Comment by keijoraamat** [comment]
Could I have input on who needs access?

**Comment by guypritchard** [comment]
This is a good question!  

I would suggest at the very least @yahya130, but ideally people on the team that are writing code so we can give access to view of the resources of at least the 'dev' environment for testing/debugging.  Other environments may not or should not give us access.

Off the top of my head from the MSFT side that would be:
@martinkearn 
@decodingahmed 
@Adele-Churchill-13
@guypritchard 
@yahya130

For the ability to view resources.

From the Netgroup side @joonasroosalung may have a better idea.

I believe we'll have at least one Service Principal which is capable of creating/modifying resources in various environments to be used by Terraform to do its work, but I think we have a separate issue for that.

@martinkearn  - anyone I'm missing here, anyone anything I've not thought about?

**Comment by yahya130** [comment]
@keijoraamat would it be worth adding the following tasks/AC's to this item? 
- Create resource group on Azure (suggested name: rg-beurokratt-dev ) 
- Create storage container on Azure manually to store the terraform state file

**Comment by martinkearn** [comment]
We have access to the resource group and can create resources and we have a service principal.
