### ISSUE TITLE
Cross: Commit Changes to Make E2E Flow Succeed

### ISSUE THREAD

**Issue by guypritchard** [buerokratt/Cross-functional-requirements#52]
AS A Developer
I WANT TO Commit a number of changes to Classifier, MockBot and DMR repositories
IN ORDER TO ensure they continue to work in concert

- [x] Commit DMR Changes
- [x] Commit MockBot Changes
- [x] Commit Classifier Changes

**Comment by martinkearn** [comment]
@guypritchard, can you tag PRs here and add yourself as Assignee? ;)
