### ISSUE TITLE
Security:  Modify Dockerfiles to create and run as a non-default User

### ISSUE THREAD

**Issue by guypritchard** [buerokratt/Cross-functional-requirements#83]
As per the [Security Architecture](https://github.com/buerokratt/Cross-functional-requirements/blob/main/docs/technical/security.md) 

In the Dockerfile, create a user and run as that non-default user:

```dockerfile
...
RUN adduser \
  --disabled-password \
  --home /app \
  --gecos '' app \
  && chown -R app /app
USER app
...
```
### Acceptance Criteria
- [x] Do this for CentOps - https://github.com/buerokratt/CentOps/pull/84
- [x] Do this for .NET DMR - https://github.com/buerokratt/DMR/pull/62
- [x] Do this for MockBot - https://github.com/buerokratt/Mock-Bot/pull/43
- [x] Do this for MockClassifier - https://github.com/buerokratt/Mock-Classifier/pull/57

**Comment by martinkearn** [comment]
Releasing the ticket in case anyone else gets to it before I do
